name: frontend_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^3.0.0
  fl_chart: ^1.0.0
  provider: ^6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2

  # Firebase or authentication can be added later if needed
  # firebase_auth: ^4.17.5
  # firebase_core: ^2.30.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # You can define asset paths like this if needed
  # assets:
  #   - assets/images/
